apiVersion: v1
kind: Secret

metadata:
  name: {{ .Values.app.name }}-aws
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-5"
    "reflector.v1.k8s.emberstack.com/reflects": "external-secrets/aws-credentials"
