apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: {{ .Values.app.name }}-database
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-10"

spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.secrets.clusterSecretStore }}
    kind: ClusterSecretStore
  target:
    name: {{ .Values.app.name }}-database
  data:
    - secretKey: connectionString
      remoteRef:
        key: "{{ .Values.app.name }}-{{ .Values.app.env }}-{{ .Values.secrets.databaseSecretName }}"
        property: value
