apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ .Values.app.name }}

spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
        - name: {{ .Values.app.name }}
          image: {{ .Values.image.repository | required "Parameter image.repository is required." }}:{{ .Values.image.tag }}
          ports:
            - containerPort: 8080

          volumeMounts:
            - name: keys
              mountPath: /app/keys
              readOnly: true

          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"

          env:
            - name: ConnectionStrings__Default
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.app.name }}-database
                  key: connectionString
            - name: EmailSenderOptions__UserName
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.app.name }}-email
                  key: userName
            - name: EmailSenderOptions__Password
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.app.name }}-email
                  key: password
            - name: AwsCredentials__AccessKey
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.app.name }}-aws
                  key: access-key-id
            - name: AwsCredentials__SecretAccessKey
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.app.name }}-aws
                  key: secret-access-key
            - name: AwsCredentials__SessionToken
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.app.name }}-aws
                  key: session-token

          envFrom:
            - configMapRef:
                name: {{ .Values.app.name }}-configs

          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 40
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 15
            failureThreshold: 3
      volumes:
        - name: keys
          secret:
            secretName: {{ .Values.app.name }}-keys
