apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: {{ .Values.app.name }}-email

spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.secrets.clusterSecretStore }}
    kind: ClusterSecretStore
  target:
    name: {{ .Values.app.name }}-email
  data:
    - secretKey: userName
      remoteRef:
        key: "{{ .Values.app.project }}-{{ .Values.app.env }}-{{ .Values.secrets.emailSecretName }}"
        property: userName
    - secretKey: password
      remoteRef:
        key: "{{ .Values.app.project }}-{{ .Values.app.env }}-{{ .Values.secrets.emailSecretName }}"
        property: password
