apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: {{ .Values.app.name }}-keys
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-5"

spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.secrets.clusterSecretStore }}
    kind: ClusterSecretStore
  target:
    name: {{ .Values.app.name }}-keys
  data:
    - secretKey: jwt-public.pem
      remoteRef:
        key: "{{ .Values.app.project }}-{{ .Values.app.env }}-{{ .Values.secrets.keysSecretName }}"
